# Generated by Django 5.2.3 on 2025-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
